language: node_js

cache: 
  directories:
    - node_modules

node_js:
  - "8"

branches:
  only:
    - nest

install:
  - npm install

script:
  - npm run test:unit

services:
  - mongodb

# before_script:
#   - sleep 15
#   - mongo my_blog --eval 'db.createUser({user:"blog-server",pwd:"blog-server",roles:[{role: "readWrite"}]});'